### ISSUE TITLE
using DBCP2 it throws Unsupport rollback error

### ISSUE THREAD

**Issue by mihayinoviki** [twilio/calcite-kudu#90]
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.apache.calcite.jdbc.CalciteMetaImpl.rollback(CalciteMetaImpl.java:805)
	at org.apache.calcite.avatica.AvaticaConnection.rollback(AvaticaConnection.java:208)
	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.passivateObject(PoolableConnectionFactory.java:440)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:110)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:649)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:531)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731)

**Comment by huukhuongnguyen** [comment]
try config below  
**dataSource.setRollbackOnReturn(false);**
