### ISSUE TITLE
calcite java.lang.Float cannot be cast to class java.lang.Double

### ISSUE THREAD

**Issue by huukhuongnguyen** [twilio/calcite-kudu#93]
class java.lang.Float cannot be cast to class java.lang.Double (java.lang.Float and java.lang.Double are in module java.base of loader 'bootstrap')
	at org.apache.calcite.avatica.util.AbstractCursor$DoubleAccessor.getDouble(AbstractCursor.java:634)
	at org.apache.calcite.avatica.util.AbstractCursor$AccessorImpl.getFloat(AbstractCursor.java:325)
	at org.apache.calcite.avatica.AvaticaResultSet.getFloat(AvaticaResultSet.java:265)

**Comment by twdsilva** [comment]
Thanks for the JIRA @huukhuongnguyen, can you please post how to reproduce the exception you are seeing?
